[project]
name = "gsea"
version = "0.1.0"
description = "FastAPI project"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "fastapi==0.121.0",
    "gseapy==1.1.10",
    "pandas==2.3.3",
    "uvicorn==0.38.0",
]
