[project]
name = "scripts"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.0",
    "clickhouse-connect>=0.9.2",
    "inquirer>=3.4.1",
    "neo4j>=6.0.3",
    "pandas>=2.3.3",
    "rich>=14.2.0",
]
